[UI-4-price-filter] add price filer as view
microservices-course-itmo/ios-client pull request #13
Opened 2020-10-02 19:55 UTC by nsolonenko

2020-10-03 08:05 UTC, BobCatC requested changes
Также нужно поправить SwiftLint Warning'и
Самый частый - Trailing Whitespace, о том, как его решить (уйдёт пара минут времени) смотри [тут](https://github.com/microservices-course-itmo/ios-client/pull/9#issuecomment-700189464)

2020-10-03 08:05 UTC, BobCatC commented on WineUp/WineUp/Modules/Catalog/Catalog/Filters/PriceFilter/PriceFilterView.swift
> +        .padding(.trailing, /*@START_MENU_TOKEN@*/10/*@END_MENU_TOKEN@*/)
Заменить `/*@START_MENU_TOKEN@*/10/*@END_MENU_TOKEN@*/` на `10`

2020-10-03 08:05 UTC, BobCatC commented on WineUp/WineUp/Modules/Catalog/Catalog/Filters/PriceFilter/PriceFilterItemButton.swift
> +struct PriceFilterItemButton: View {
Стоит добавить превью

2020-10-03 08:05 UTC, BobCatC commented on WineUp/WineUp/Modules/Catalog/Catalog/Filters/PriceFilter/PriceFilterItemView.swift
> +struct PriceFilterItemView: View {
Стоит добавить превью

2020-10-03 08:05 UTC, BobCatC commented on WineUp/WineUp/Modules/Catalog/Catalog/FiltersBar/CatalogFiltersBarView.swift
> +        VStack() {
Зачем тут скобки?) SwiftLint негодует

2020-10-03 08:48 UTC, dimonker requested changes

2020-10-03 08:48 UTC, dimonker commented on WineUp/WineUp/Modules/Catalog/Catalog/Filters/PriceFilter/PriceFilterView.swift
> +        .padding(.trailing, /*@START_MENU_TOKEN@*/10/*@END_MENU_TOKEN@*/)
лучше наверное в константы вынести
`private enum Constants {
   static let startMenuToken = 10
}
`
и использовать так `Constants.startMenuToken`

2020-10-03 08:48 UTC, dimonker commented on WineUp/WineUp/Modules/Catalog/Catalog/Filters/PriceFilter/PriceFilterItemView.swift
> +                RoundedRectangle(cornerRadius: 25)
тоже надо бы все числа в константы вынести

2020-10-03 08:48 UTC, dimonker commented on WineUp/WineUp/Modules/Catalog/Catalog/Filters/PriceFilter/PriceFilterView.swift
> +struct PriceFilterViewPreviews: PreviewProvider {
#if DEBUG

2020-10-03 08:48 UTC, dimonker commented on WineUp/WineUp/Modules/Catalog/Catalog/Filters/PriceFilter/PriceFilterView.swift
> +}
#endif

2020-10-03 13:45 UTC, nsolonenko commented on WineUp/WineUp/Modules/Catalog/Catalog/Filters/PriceFilter/PriceFilterView.swift
> +        .padding(.trailing, /*@START_MENU_TOKEN@*/10/*@END_MENU_TOKEN@*/)
Тогда уже лучше отдельный класс Constants завести(думаю еще пригодится) и делать к нему extension в такие моменты, но уже как вариант на будущее + если мы уже и говорим о верстке, то думаю не обязательно все значения накидывать в константы, так как это не имеет никакого смысла, даже к нормальной переменной их не присвоить, а по поводу этого кейса, я просто недоглядел.

2020-10-03 13:46 UTC, nsolonenko commented on WineUp/WineUp/Modules/Catalog/Catalog/FiltersBar/CatalogFiltersBarView.swift
> +        VStack() {
Миссклик

2020-10-03 17:34 UTC, BobCatC commented on WineUp/WineUp/Modules/Catalog/Catalog/Filters/PriceFilter/PriceFilterItemView.swift
> +                RoundedRectangle(cornerRadius: 25)
@dimonker, давай обсудим плюсы и минусы предложенного тобой подхода
\+ Выносим константы в отдельную сущность. Безусловно плюс, ведь мы отделяем описание структуры нашего _гибкого_ UI и жёстко определяющие его константы;
± Single Source of Truth. Как бы да, но, учитывая, что константа будет использована только в одном мете, теряет свой смысл;
\- Уменьшение читаемости. Если раньше я видел `RoundedRectangle(cornerRadius: 25)`, то теперь я увижу `RoundedRectangle(cornerRadius: Constants.overlayRectCornerRadius)` и буду вынужден искать глазами значение константы.

Также неясно, почему, если мы всё же выносим числа, мы забываем про enum'мы (например, `.foregroundColor(.primary)`), хотя это точно такие же константы

2020-10-04 15:29 UTC, BobCatC approved these changes

2020-10-04 15:37 UTC, dimonker approved these changes

2020-10-04 17:13 UTC, merged