UI-6 recommendation filter
microservices-course-itmo/ios-client pull request #14
Opened 2020-10-04 11:20 UTC by dimonker

2020-10-04 17:11 UTC, BobCatC requested changes
По написанному коду вопросов нет
Только я тут не вижу контейнер фильтров
Задача UI-6: "Реализация контента фильтра по рекомендациям и **контейнера фильтров**"

2020-10-05 13:06 UTC, dimonker commented
Сорян, просто увидел скрин с фильтром, быстро пробежался по описанию и не заметил, что нужно реализовать контейнер

2020-10-05 13:24 UTC, BobCatC commented
Успеешь в течение полутора часов доделать контейнер?)
Или занят сейчас?

2020-10-05 13:27 UTC, BobCatC commented
По сути, это просто View, которая должна уметь:
1. Затемнять часть экрана сверху, когда её презентуют
2. Показывать некоторый контент внутри себя плюс кнопки "Применить" и "сбросить" (пока обеих опционально настраиваемый)

В исходном описании указан ещё заголовок в контейнере, но все реализовали заголовок в контенте, так что с ним отмена

2020-10-05 13:47 UTC, dimonker commented
Не успею
Давай на некст спринте отдельной задачей доделаю

2020-10-05 14:10 UTC, BobCatC commented
Хорошо
Тогда этот PR можно мёржить

2020-10-05 14:10 UTC, BobCatC approved these changes
Контейнер будет реализован отдельно

2020-10-05 14:10 UTC, merged