UI-5-added-color-sugar-filters
microservices-course-itmo/ios-client pull request #15
Opened 2020-10-04 12:30 UTC by Vlad-9

2020-10-04 13:39 UTC, dimonker requested changes

2020-10-04 13:39 UTC, dimonker commented on WineUp/WineUp/Modules/Catalog/Catalog/Filters/ColorFilter/ColorFilterItemView.swift
> +            HStack(alignment: .center) { Image(systemName: self.isChecked ? "checkmark.square.fill": "square").foregroundColor(self.isChecked ? Color(red: 158 / 255.0, green: 51 / 255.0, blue: 75 / 2
Страшилка однострочная

2020-10-04 13:39 UTC, dimonker commented on WineUp/WineUp/Modules/Catalog/Catalog/Filters/SugarFilter/SugarFilterItemView.swift
> +            HStack(alignment: .center) { Image(systemName: self.isChecked ? "checkmark.square.fill": "square").foregroundColor(self.isChecked ? Color(red: 158 / 255.0, green: 51 / 255.0, blue: 75 / 2
опять страшилка

2020-10-04 13:39 UTC, dimonker commented on WineUp/WineUp/Modules/Catalog/Catalog/Filters/ColorFilter/ColorFilterItemButton.swift
> +struct ColorFilterItemButton: View {
Копипаста с SugarFilterItemButton

2020-10-04 13:39 UTC, dimonker commented on WineUp/WineUp/Modules/Catalog/Catalog/Filters/SugarFilter/SugarFilterItemView.swift
> +    var isChecked: Bool
можно сделать @Binding

2020-10-04 13:39 UTC, dimonker commented on WineUp/WineUp/Modules/Catalog/Catalog/Filters/SugarFilter/SugarFilterItemButton.swift
> +            SugarFilterItemView(item: item, isChecked: self.isChecked).padding()
а тут isChecked: $isChecked

2020-10-04 13:39 UTC, dimonker commented on WineUp/WineUp/Modules/Catalog/Catalog/Filters/SugarFilter/SugarFilterItemButton.swift
> +            SugarFilterItemView(item: item, isChecked: self.isChecked).padding()
self лишнее

2020-10-04 13:39 UTC, dimonker commented on WineUp/WineUp/Modules/Catalog/Catalog/Filters/ColorFilter/ColorFilterView.swift
> +    private func itemDidTap(_ item: ColorFilterItemModel) {
Эта функция не используется

2020-10-04 13:39 UTC, dimonker commented on WineUp/WineUp/Modules/Catalog/Catalog/Filters/ColorFilter/ColorFilterView.swift
> +    var onItemTap: OnItemTap?
действия по идее должны быть во ViewModel

2020-10-04 15:32 UTC, BobCatC commented on WineUp/WineUp/Modules/Catalog/Catalog/Filters/ColorFilter/ColorFilterItemView.swift
> +            HStack(alignment: .center) { Image(systemName: self.isChecked ? "checkmark.square.fill": "square").foregroundColor(self.isChecked ? Color(red: 158 / 255.0, green: 51 / 255.0, blue: 75 / 2
Страшна

2020-10-04 16:30 UTC, BobCatC requested changes
1. Нет заголовков файлов (имя файла, кто и когда его создал)
2. Файлы SuperFilterView и ColorFilterView (аналогично их subview) - просто копии друг друга, нужна более обобщённая реализация
3. Есть мелкие замечания по коду

Насчёт неиспользуемых функций и `Toggle` VS `Button`, сейчас взаимодействия всё равно нет, нужен только UI, на это можно забить, а в некст спринте я могу этот момент поправить (уже есть идея, как правильно связать данные через `State` и `Binding`)

2020-10-04 16:30 UTC, BobCatC commented on WineUp/WineUp/Modules/Catalog/Catalog/Filters/ColorFilter/ColorFilterItemButton.swift
> +#if DEBUG
Как так получилось, что `ColorFilterItemButtonPreview` оказался внутри ColorFilterItemButton?)

2020-10-04 16:30 UTC, BobCatC commented on WineUp/WineUp/Modules/Catalog/Catalog/Filters/ColorFilter/ColorFilterView.swift
> +        VStack {
Вложенный `VStack` точно нужен?

2020-10-04 16:30 UTC, BobCatC commented on WineUp/WineUp/Modules/Catalog/Catalog/Filters/ColorFilter/ColorFilterView.swift
> +    var onItemTap: OnItemTap?
Видимо, имелось в виду, что инстанс, который создаёт `ColorFilterView` передаёт этой вьюхе в конструкторе лямбда функцию, чтобы реагировать на изменения. По-аналогии работает Button (у кнопки также есть callback function поле `action`)
@dimonker, или в чём-то другом вопрос?

2020-10-04 16:30 UTC, BobCatC commented on WineUp/WineUp/Modules/Catalog/Catalog/Filters/SugarFilter/SugarFilterItemButton.swift
> +struct SugarFilterItemButtonPreview: PreviewProvider {
Аналогично неясно, как этот тут оказалось

2020-10-04 16:30 UTC, BobCatC commented on WineUp/WineUp/Modules/Catalog/Catalog/Filters/SugarFilter/SugarFilterItemButton.swift
> +
Перевод строки?)

2020-10-04 16:30 UTC, BobCatC commented on WineUp/WineUp/Modules/Catalog/Catalog/Filters/SugarFilter/SugarFilterItemView.swift
> +            HStack(alignment: .center) { Image(systemName: self.isChecked ? "checkmark.square.fill": "square").foregroundColor(self.isChecked ? Color(red: 158 / 255.0, green: 51 / 255.0, blue: 75 / 2
Совершенно не стоит реализовывать полностью совпадающий UI. Гораздо лучше было бы вместо этих мучений с `Image`, обёрнутым в `Button`, использовать `Toggle` (switch по-русски). Его можно будет и забиндить, и убрать этот `onItemTap` (который должен использоваться как раз с кнопкой, а не с switch'ом)

2020-10-04 16:30 UTC, BobCatC commented on WineUp/WineUp/Modules/Catalog/Catalog/Filters/SugarFilter/SugarFilterView.swift
> +
Перевод строки?)

2020-10-04 16:30 UTC, BobCatC commented on WineUp/WineUp/Modules/Catalog/Catalog/Filters/ColorFilter/ColorFilterItemButton.swift
> +
Перевод строки?)

2020-10-07 05:51 UTC, BobCatC approved these changes

2020-10-07 12:29 UTC, dimonker approved these changes

2020-10-07 13:36 UTC, merged