[UI-9-verification-view] add verification view
microservices-course-itmo/ios-client pull request #18
Opened 2020-10-10 08:52 UTC by nsolonenko

2020-10-11 11:49 UTC, BobCatC requested changes
В первую очередь необходимо сделать `rebase` от ветки sprint/2020-10-05, потому что сейчас ветка UI-9-verification-view стартует от предыдущего спринта

2020-10-11 12:23 UTC, BobCatC requested changes

2020-10-11 12:23 UTC, BobCatC commented on WineUp/WineUp/Modules/Authorization/VerificationCodeView.swift
> +                            .font(/*@START_MENU_TOKEN@*/.title/*@END_MENU_TOKEN@*/)
Токен

2020-10-11 12:23 UTC, BobCatC commented on WineUp/WineUp/Modules/Authorization/VerificationCodeView.swift
> +        UINavigationBar.appearance().largeTitleTextAttributes = [.font: largeFont]
Точно убрать, для 'LargeTitle' есть метод `navigationBarTitleDisplayMode`, за точными шрифтами, как в UX, гнаться не стоит

2020-10-11 12:23 UTC, BobCatC commented on WineUp/WineUp/Modules/Authorization/VerificationCodeView.swift
> +        NavigationView {
`NavigationView` будет вне этого модуля, отсюда его можно и нужно просто убрать

2020-10-11 12:23 UTC, BobCatC commented on WineUp/WineUp/Modules/Authorization/VerificationCodeView.swift
> +    var body: some View {
На данный момент эта длинная конва из объектов внутри `body` просто нечитаема. Нужно либо разделить её на SubView, либо хотя бы расставить комментарии, которые бы разбили код на компоненты

2020-10-11 12:23 UTC, BobCatC commented on WineUp/WineUp/Modules/Authorization/VerificationCodeView.swift
> +    @State private var code: String = ""
Создать `ViewModel` и вынести код туда

2020-10-11 12:23 UTC, BobCatC commented on WineUp/WineUp/Modules/Authorization/VerificationCodeView.swift
> +struct VerificationCodeViewPreviews: PreviewProvider {
Обернуть в #if DEBUG

2020-10-11 16:45 UTC, nsolonenko commented on WineUp/WineUp/Modules/Authorization/VerificationCodeView.swift
> +        NavigationView {
Если он будет вне, я тогда убираю title Wine UP  ибо логично будет его закинуть в navigationbar

2020-10-11 18:36 UTC, BobCatC commented on WineUp/WineUp/Modules/Authorization/VerificationCodeView.swift
> +        NavigationView {
Не совсем
Твоя View - экран
Он для себя определяет Title NavigationBar’а

2020-10-11 18:37 UTC, BobCatC commented on WineUp/WineUp/Modules/Authorization/VerificationCodeView.swift
> +        NavigationView {
Ведь Title нельзя определить для всего бара
Он указывается у View
Или в SwiftUI что-то поменялось?

2020-10-11 19:08 UTC, nsolonenko commented on WineUp/WineUp/Modules/Authorization/VerificationCodeView.swift
> +        NavigationView {
Ну как я вижу мы оборачиваем вью в navigation view  что бы иметь взаимодействие с компонентами navigation view ,  и емли мы вынесем в отдельный модуль, все равно придется оборачивать все элементы, но возможно я просто не нашел рабочего момента как без этого взаимодействовать

2020-10-11 19:23 UTC, nsolonenko commented on WineUp/WineUp/Modules/Authorization/VerificationCodeView.swift
> +                            .font(/*@START_MENU_TOKEN@*/.title/*@END_MENU_TOKEN@*/)
resolve

2020-10-11 19:23 UTC, nsolonenko commented on WineUp/WineUp/Modules/Authorization/VerificationCodeView.swift
> +        UINavigationBar.appearance().largeTitleTextAttributes = [.font: largeFont]
resolve

2020-10-11 19:23 UTC, nsolonenko commented on WineUp/WineUp/Modules/Authorization/VerificationCodeView.swift
> +    var body: some View {
resolve

2020-10-11 19:23 UTC, nsolonenko commented on WineUp/WineUp/Modules/Authorization/VerificationCodeView.swift
> +    @State private var code: String = ""
resolve

2020-10-11 19:23 UTC, nsolonenko commented on WineUp/WineUp/Modules/Authorization/VerificationCodeView.swift
> +struct VerificationCodeViewPreviews: PreviewProvider {
resolve

2020-10-12 08:48 UTC, BobCatC reviewed
Указал один момент, но он под вопросом
В остальном - всё исправлено

2020-10-12 08:48 UTC, BobCatC commented on WineUp/WineUp/Modules/Authorization/VerificationCodeViewModel.swift
> +     var code: String = ""
Без `@Published` разве это будет работать?
@dimonker, что думаешь?

2020-10-12 09:08 UTC, dimonker commented on WineUp/WineUp/Modules/Authorization/VerificationCodeViewModel.swift
> +     var code: String = ""
Нет, не будет. `@ObservableObject` отслеживает только поля помеченные как `@Published`

https://heckj.github.io/swiftui-notes/#reference-observableobject
> Classes implementing ObservedObject are also expected to use @Published to provide notifications of changes on specific properties, or to optionally provide a custom announcement that indicates the object has changed.

2020-10-12 09:14 UTC, nsolonenko commented on WineUp/WineUp/Modules/Authorization/VerificationCodeViewModel.swift
> +     var code: String = ""
fixed

2020-10-12 09:17 UTC, BobCatC approved these changes

2020-10-12 09:17 UTC, merged