UI-8 Create Authorization view
microservices-course-itmo/ios-client pull request #19
Opened 2020-10-10 21:42 UTC by Vlad-9

Add phoneNumber authorization view and phone formatter

2020-10-10 23:19 UTC, alexstrive commented on WineUp/WineUp/Modules/Authorization/PhoneNumberAuthorization/PhoneAuthorizationView.swift
> +struct PhoneView_Previews: PreviewProvider {
@BobCatC тут вроде #debug нужен?

2020-10-10 23:19 UTC, alexstrive commented on WineUp/WineUp/Modules/Authorization/PhoneNumberAuthorization/PhoneAuthorizationView.swift
> +            }).padding() .navigationBarTitle("WineUp")
И тут наверное перенос строки был забыт?)

2020-10-11 04:25 UTC, BobCatC commented on WineUp/WineUp/Modules/Authorization/PhoneNumberAuthorization/PhoneAuthorizationView.swift
> +struct PhoneView_Previews: PreviewProvider {
Абсолютно верно

2020-10-11 04:26 UTC, BobCatC commented on WineUp/WineUp/Modules/Authorization/PhoneNumberAuthorization/PhoneAuthorizationView.swift
> +            }).padding() .navigationBarTitle("WineUp")
Да, для лучшей читаемости стоит добавить

2020-10-11 12:40 UTC, BobCatC requested changes
Также нужно ставить переводы строки между объявлениями (см. остальной код в проекте). Если проблемы с 'Trailing Whitespace', вот [тут](https://github.com/microservices-course-itmo/ios-client/pull/9#issuecomment-700189464) есть объяснение, как её решить

2020-10-11 12:40 UTC, BobCatC commented on WineUp/WineUp/Modules/Authorization/PhoneNumberAuthorization/PhoneNumberModel.swift
> +class PhoneNumberModel: ObservableObject {
Это разве не `ViewModel`?

2020-10-11 12:40 UTC, BobCatC commented on WineUp/WineUp/Modules/Authorization/PhoneNumberAuthorization/PhoneNumberModel.swift
> +import  SwiftUI
Лишний пробел

2020-10-11 12:40 UTC, BobCatC commented on WineUp/WineUp/Modules/Authorization/PhoneNumberAuthorization/PhoneNumberModel.swift
> +    let objectWillChange = ObservableObjectPublisher()
Если перед `correctNum` поставить `@Published`, то разве оно не заработает?
При этом после редактирования значения в `TextField`, к которому привязан `correctNum`, нужно просто вызвать метод у ViewModel'и, который отформатирует новое значение

2020-10-11 12:40 UTC, BobCatC commented on WineUp/WineUp/Modules/Authorization/PhoneNumberAuthorization/PhoneNumberModel.swift
> +    func formatter(mask: String, phone: String) -> String {
Хорошо бы к такой функции добавить Unit тест, чтобы показать, как она работает
Иначе приходится вчитываться в её код
Кстати, красиво решение с маской)

2020-10-11 12:40 UTC, BobCatC commented on WineUp/WineUp/Modules/Authorization/PhoneNumberAuthorization/PhoneAuthorizationView.swift
> +        NavigationView {
`NavigationView` можно и нужно убрать, в него будет обёрнута вся View

2020-10-11 12:40 UTC, BobCatC commented on WineUp/WineUp/Modules/Authorization/PhoneNumberAuthorization/PhoneAuthorizationView.swift
> +                Text("Введите номер телефона для авторизации").font(.system(size: 25)).lineLimit(2)
Добавить переводы строки

2020-10-11 12:40 UTC, BobCatC commented on WineUp/WineUp/Modules/Authorization/PhoneNumberAuthorization/PhoneAuthorizationView.swift
> +                    TextField("+7 (9XX) XXX-XX-XX", text: $phoneNumber.correctNum) .multilineTextAlignment(.leading)
Перевод строки

2020-10-11 12:40 UTC, BobCatC commented on WineUp/WineUp/Modules/Authorization/PhoneNumberAuthorization/PhoneAuthorizationView.swift
> +                        .padding(.horizontal, 26.0).font(.system(size: 25))
Перевод строки

2020-10-11 12:40 UTC, BobCatC commented on WineUp/WineUp/Modules/Authorization/PhoneNumberAuthorization/PhoneAuthorizationView.swift
> +    let chColor = Color(red: 158 / 255.0, green: 51 / 255.0, blue: 75 / 255.0)
Что означает `chColor` (я про нэйминг)?

2020-10-11 12:40 UTC, BobCatC commented on WineUp/WineUp/Modules/Authorization/PhoneNumberAuthorization/PhoneAuthorizationView.swift
> +                        .frame(minWidth: 0, maxWidth: .infinity)
В чём смысл этой строки?

2020-10-11 12:40 UTC, BobCatC commented on WineUp/WineUp/Modules/Authorization/PhoneNumberAuthorization/PhoneAuthorizationView.swift
> +                    Button(action: {}) {
Учитывая размер кода этой кнопки, возможно, стоит вынести её, как отдельную View?

2020-10-12 19:20 UTC, BobCatC commented
Необходим `git rebase sprint/2020-10-12`

2020-10-12 20:12 UTC, Vlad-9 commented
> Необходим `git rebase sprint/2020-10-12`
Сделано

2020-10-13 08:17 UTC, BobCatC approved these changes

2020-10-13 08:17 UTC, merged