Добавление параметров запроса получения винных позиций
microservices-course-itmo/ios-client pull request #48
Opened 2020-11-22 17:10 UTC by dimonker

Добавление параметров запроса получения винных позиций

2020-11-29 20:18 UTC, BobCatC requested changes
Очень красивое решение с билдером, но пока не проверял, как оно работает, так как кластер снова недоступен.

Оставил несколько небольших комментариев

2020-11-29 20:18 UTC, BobCatC commented on WineUp/WineUp/Modules/Catalog/Catalog/CatalogView+ViewModel.swift
> +            RealWinePositionWebRepository(session: URLSession.shared, baseURL: "http://77.234.215.138:48080/catalog-service")
Глянь в `container.services`, там уже есть этот сервис

2020-11-29 20:18 UTC, BobCatC commented on WineUp/WineUp/Modules/Catalog/Catalog/CatalogView+ViewModel.swift
> -            initStaticData()
Если удалил вызов, удали и определение метода

2020-11-29 20:18 UTC, BobCatC commented on WineUp/WineUp/Repositories/Web/WinePositionWebRepository/WinePositionFilters.swift
> +    let attribute_name: WinePositionSortableCriteries
Тут можно спокойно использовать camelCase, `JSONEncoder` умеет преобразовать в snake, если нужно (см. параметры конструктора `APICall`)

2020-11-29 20:18 UTC, BobCatC commented on WineUp/WineUp/Repositories/Web/Utils/APICall.swift
> +    var queryItems: [URLQueryItem]?
Если `QueryParameters` больше не используется, то его объявление можно удалить.

Кстати, в чём преимущество использования сырого `URLQueryItem`? Кажется, что передавать словарь удобнее, чем список `URLQueryItem`'ов, нет?

2020-11-29 20:19 UTC, BobCatC commented on WineUp/WineUp/Repositories/Web/WinePositionWebRepository/WinePositionFilters.swift
> +    let attribute_name: WinePositionSortableCriteries
Кстати, для всех методов каталога я уже указал преобразовывать наш camelCase в snake_case, который указан в доках к каталогу, так что достаточно будет просто переименовать переменную в `attributeName` и всё должно заработать

2020-11-29 20:23 UTC, dimonker commented on WineUp/WineUp/Modules/Catalog/Catalog/CatalogView+ViewModel.swift
> -            initStaticData()
случайно удалил

2020-11-29 20:26 UTC, BobCatC commented
И ещё. У нас появился достаточно интересный Web репозиторий - `TrueWinePositionRepository`. Суть в том, что каталог добавил возможность скачивать модели данных с вложенными, а не с ссылками на них (например, в обычном запросе винных позиций я буду получать `wineId` внутри, а в True версии будет `wine` со всеми вложенными полями)

Так что нужно добавить эти параметры запроса и в `TrueWinePositionRepository`

2020-11-29 20:33 UTC, dimonker commented on WineUp/WineUp/Repositories/Web/WinePositionWebRepository/WinePositionFilters.swift
> +    let attribute_name: WinePositionSortableCriteries
наверное, это не совсем хорошее решение ставить параметр для преобразования в snake у JSONEncoder, тк они сами на api мешают snake и camel (см WinePositionCriteries)

2020-11-29 20:49 UTC, dimonker commented on WineUp/WineUp/Repositories/Web/Utils/APICall.swift
> +    var queryItems: [URLQueryItem]?
Были траблы с мержем изменений с твоего предыдущего коммита, поэтому такое получилось. Твое решение выглядет лучше, поправлю

2020-12-01 18:51 UTC, BobCatC commented on WineUp/WineUp/Repositories/Web/WinePositionWebRepository/WinePositionFilters.swift
> +    let attribute_name: WinePositionSortableCriteries
Параметр на преобразование в snake стоит у каждого APICall, то есть каждый запрос сам для себя определяет, как нужно его декодить/енкодить. Думаешь, это плохое решение?

То, что каталог с юзером не договорились о стиле - это, конечно, некрасиво.

2020-12-01 19:03 UTC, BobCatC approved these changes

2020-12-01 19:03 UTC, BobCatC commented on WineUp/WineUp/Repositories/Web/WinePositionWebRepository/WinePositionFilters.swift
> +    let attribute_name: WinePositionSortableCriteries
В моём варианте как раз модель данных не зависит от правил snake/camel

2020-12-01 19:03 UTC, dimonker commented on WineUp/WineUp/Repositories/Web/WinePositionWebRepository/WinePositionFilters.swift
> +    let attribute_name: WinePositionSortableCriteries
А, тупанул, раз это параметр по умолчанию и каждый запрос может изменить его - то все норм

2020-12-01 19:03 UTC, merged