UI-19 APNS Registration
microservices-course-itmo/ios-client pull request #51
Opened 2020-11-30 13:30 UTC by Vlad-9

2020-11-30 18:03 UTC, BobCatC requested changes
На устройство не приходит APNS токен. Если убрать вызов `FirebaseApp.configure()`, то всё работает. Возможно, придётся использовать FirebaseMessaging, чтобы уже из него вытащить токен APNS.

Необходимо поправить SwiftLint warning'и

2020-11-30 18:04 UTC, BobCatC commented
Кстати, зачем тут файл `WineUpStaging.entitlements`?

2020-11-30 18:06 UTC, BobCatC commented
@Vlad-9, кроме этого нужно поискать, как в `project.yaml` добавить _Capability Push Notifications_

2020-12-01 19:12 UTC, dimonker commented
> Кстати, зачем тут файл `WineUpStaging.entitlements`?

вроде для того чтоб активировать _Capability Push Notifications_

2020-12-01 19:12 UTC, dimonker commented
> @Vlad-9, кроме этого нужно поискать, как в `project.yaml` добавить _Capability Push Notifications_
> 
> @dimonker, не поможешь?

возможно, это поможет
https://github.com/yonaskolb/XcodeGen/issues/540#issuecomment-475933180

2020-12-01 19:13 UTC, BobCatC commented
Но, когда я добавлял Push Notifications в Capability, у меня автоматически создавался файл `WineUp.entitlements` (без суффикса Staging)

2020-12-01 19:24 UTC, BobCatC commented
@Vlad-9 , в общем задача - добавить FirebaseMessaging и оттуда вытаскивать APNS токен. Либо найти какое-то другое решение.

2020-12-07 12:05 UTC, BobCatC approved these changes

2020-12-07 12:06 UTC, merged