Create ui in catalog row view
microservices-course-itmo/ios-client pull request #9
Opened 2020-09-27 14:01 UTC by PhotolocaDeveloper

2020-09-27 14:15 UTC, dimonker requested changes

2020-09-27 14:15 UTC, dimonker commented on WineUp/WineUp/Modules/Catalog/Catalog/CatalogRow/CatalogRowRatingView.swift
> +                    Image(systemName: "star.fill")
`ForEach(1...5) { index in`

2020-09-27 14:20 UTC, dimonker commented
Еще WineUp.xcodeproj надо бы удалить

2020-09-27 20:14 UTC, BobCatC requested changes
WineUp.xcodeproj удалил (нужно запулить локальную ветку)
Есть незначительные замечания

2020-09-27 20:14 UTC, BobCatC commented on WineUp/WineUp/Modules/Catalog/Catalog/CatalogRow/CatalogRowDiscountView.swift
> +    // MAR: - View
*MARK (typo)

2020-09-27 20:14 UTC, BobCatC commented on WineUp/WineUp/Modules/Catalog/Catalog/CatalogRow/CatalogRowInfoView.swift
> +                Text("Подходит вам на 75%")
Для этого есть поле "chemistry" в CatalogItemModel

2020-09-27 20:14 UTC, BobCatC commented on WineUp/WineUp/Modules/Catalog/Catalog/CatalogRow/CatalogRowPreviewImageView.swift
> +    // MAR: - View
*MARK (typo)

2020-09-27 20:16 UTC, BobCatC commented
Также нужно пофиксить Warning'и, выводимые SwiftLint

2020-09-28 17:46 UTC, PhotolocaDeveloper commented on WineUp/WineUp/Modules/Catalog/Catalog/CatalogRow/CatalogRowInfoView.swift
> +                Text("Подходит вам на 75%")
Я не эксперт, но мне кажется ужасный нейминг для процента совместимости. compatibilityPercent - было бы намного понятнее.

2020-09-28 17:49 UTC, BobCatC commented on WineUp/WineUp/Modules/Catalog/Catalog/CatalogRow/CatalogRowInfoView.swift
> +                Text("Подходит вам на 75%")
Ок
Сам переименуешь?

2020-09-28 17:56 UTC, BobCatC commented
Насчёт Warning'ов от SwiftLint
Огромная их часть связана с TrailingWhitespace, проблема которых в увеличении количества Merge конфликтов
Чтобы TrailingWhitespace не оставались в коде, в Xcode есть настройка (automatically trim trailing whitestapce) 
<img width="828" alt="image" src="https://user-images.githubusercontent.com/31915855/94468350-f2006380-01cc-11eb-8882-5c9c13a5b7e6.png">

2020-09-28 18:07 UTC, BobCatC requested changes
Можешь переименовать _chemistry_
Нужно пофиксить SwiftLint Warning' и (в частности, настроить trailing whitespace, более подробно описал в комменте выше)

2020-09-28 18:20 UTC, PhotolocaDeveloper commented
C trailing whitespace поправил 
Интересная штука xcodeGen, не слышал ранее о ней. 

Там остались два замечания свифт линта, связанные с использованием картинок. 
1) Совсем непонятно как решать, так как UIImage(named: "") - не то, рекомендует юзать literal (что не самое лучшее решение), но на него также ругается 
2) Да и хуй с ним, думаю, все равно тестовые данные которые мы выпилим. По идее можно было сделать через RSwift, но он у меня не заводиться, а сейчас разбираться максимально лень с этим

2020-09-28 18:25 UTC, BobCatC commented
Насчёт ImageLiteral согласен
Странно, что Rswift не завёлся у тебя, я у себя попробовал - всё ок
<img width="516" alt="image" src="https://user-images.githubusercontent.com/31915855/94470890-f3cc2600-01d0-11eb-9867-451d91981149.png">

Оставь лучше код с Rswift (пусть у тебя и не работает), потом разберёшься. Чтобы сейчас не мёржить не совсем валидный код.

Вот строки из скрина: `R.image.red_and_white_wine_122015()!` и `R.image.image4()!`

2020-09-28 18:26 UTC, BobCatC commented
Да, с тестовыми данными не важно

2020-09-28 18:26 UTC, BobCatC commented
Будешь _chemistry_ переименовывать или я мёржу?

2020-09-28 18:41 UTC, BobCatC approved these changes

2020-09-28 18:44 UTC, dimonker approved these changes

2020-09-28 18:45 UTC, merged